### ISSUE TITLE
Line Heights with Ems

### ISSUE THREAD

**Issue by ChrisSargent** [hiulit/Sassy-Gridlover#12]
Hi, thanks for making this, it's very useful!

So, I'm just working on a site where I'm using EMs for font sizing. I've noticed that when using headers that break on to more than one line, the layout is going slightly off the grid. (it seems to work fine if I switch the units to rems or px but that breaks the ease of modifying the body font size)

Here's my Sass

```sass
$sgl-base-font-size: 12
$sgl-base-line-height: 2
$sgl-base-unit: 'em'
$sgl-scale-factor: $GOLDEN_SECTION

html
  background-image: linear-gradient(to bottom, hsla(200, 100%, 50%, .3) 1px, transparent 1px)
  background-position: left -1px
  background-repeat: repeat
  background-size: round(($sgl-base-font-size * $sgl-base-line-height)) * 1px round(($sgl-base-font-size * $sgl-base-line-height)) * 1px

body
  +sgl-body

h1
  +sgl-heading(3)

```

And some example HTML

```html
<h1>Some long text that will wrap on to more than one line. Some more long text that will wrap on to more than one line. Some more long text that will wrap on to more than one line</h1>
<p>Content</p>
```

I wonder if one of the calculations is a bit off or if some of the roundings are putting a bit out of whack. Interestingly, if you set the base font size to 48px it lines up correctly.

Also, even though I was setting the debug option to true, it wasn't outputting the CSS for the html so I had to add it in manually.

Thanks,

Chris

**Comment by ChrisSargent** [comment]
Also - is there any quick way to tighten up the line heights on some headings? Or should it be overwritten in the SASS?

Chris

**Comment by hiulit** [comment]
Hi there @ChrisSargent

First of all, I'm glad you like it :)
And yes, you are right. When using `em` the layout goes slightly off the grid :(

First I thought it was because of the decimal precision. I did a little research on the subject and I found this issue https://github.com/sass/sass/issues/1122.

By default, Sass has a decimal precision of 5 (and it seems that it's not gonna change any time soon) and the Gridlover app uses a decimal precision of 16, so I thought this might be it.

But then I realized that what the Gridlover app actually does is to `ceil()` the decimals when using `em` (or at least in some cases, I don't know exactly).
So, instead of outputting `1.2222222222222222em`, they output `1.2222222222222223em`.
That's what does the trick, I think.

I borrowed some functions from @terkel https://gist.github.com/terkel/4373420 to help with this matter and I think I got it working.

I'll release a new version with these changes and I would really love to hear your feedback!

P.S. Speaking of the `debug mode`. Maybe I wasn't clear enough or maybe it should be done differently, but right now it must be declared in your `_variables.scss` or `_config.scss` or the like in order to work. Basically, it must be declared before the `@import "sassy-gridlover"`.
Do you think it could be implemented in another way? Maybe with a mixin?

P.P.S. I'm afraid there's no easy way to do what you want with the line heights. This project is essentially a 'Sass port' of the [Gridlover app](http://www.gridlover.net/try) and they don't provide this kind of functionality.
You could try playing with the default `line-height` and `scale-factor` and see if you get something more to your liking. But apart from that, I think it's best if you just override them yourself.

**Comment by hiulit** [comment]
Hey @ChrisSargent 

I've just released a new version https://github.com/hiulit/Sassy-Gridlover/releases/tag/v3.1.1 with some changes regarding this issue ;)

**Comment by ChrisSargent** [comment]
Awesome, I'll try to update asap but it'll probably be a day or two.

Chris
